import Feed from "@components/Feed";

const Home = () => {
  return (
    <section className="w-full flex-center flex-col">
     <h1 className="head_text text-center">
        Discover & Share
        <br className="max-md:hidden" />
        <span className="orange_gradient
        text-center">AI-Powered Prompts</span>
     </h1>

     <p className="desc text-center">
        Promptopia is a platform for discovering and sharing AI-powered prompts. 
        <br className="max-md:hidden" />
        Our prompts are generated by a state-of-the-art language model, 
        <br className="max-md:hidden" />
        and are designed to inspire creativity and spark new ideas. 
        <br className="max-md:hidden" />
        Whether you're a writer, artist, or just looking for a fun challenge, 
        <br className="max-md:hidden" />
        Promptopia has something for everyone.
     </p>
    
    <Feed />
    </section>
  )
}

export default Home;